let constants = {
  CHANGE: "FORM_CHANGE",
  SET_DRIVER_FORM: "SET_DRIVER_FORM",
  EDIT_DRIVER_FORM: "EDIT_DRIVER_FORM",
  SET_LICENCES_FORM: "SET_LICENCES_FORM",
  CREATE_LICENCE_FORM: "CREATE_LICENCE_FORM",
  EDIT_LICENCE_FORM: "EDIT_LICENCE_FORM",
  DELETE_LICENCE_FORM: "DELETE_LICENCE_FORM",
  RESET_FORM: "RESET_FORM",
  API_ERRORS: "API_ERRORS",
  CLEAR_ERRORS: "CLEAR_ERRORS",
  DELETE_FIELD_ERROR: "DELETE_FIELD_ERROR",
  SET_FIELD_ERROR: "SET_FIELD_ERROR",
  SET_LICENCES: "SET_LICENCES"
};

export default constants;
